### ISSUE TITLE
pdf not displaying inline

### ISSUE THREAD

**Issue by Runtzel** [DeepSouthDH/deepsouthdh.github.io#2]

**Comment by danieljohnevans** [comment]
@Runtzel -- remember you want to display the actual image. You're currently linking to the GH page (right click on img to actually link to it)

Also think about the size of the img. Hillary has included sizing info inline but it is in pixels. You may want name the element with a div tag and then select and resize it using css. This might help: https://imagekit.io/blog/how-to-resize-image-in-html/ but I'm happy to set up a call to walk you through this.

Good luck! Feel free to ping with questions

**Comment by hillaryAHR** [comment]
Thank you for that link @danieljohnevans!  I didn't really size it correctly (just was playing with the ratios), so this will help us reconfigure.
